{% set name = "fugue" %}
{% set version = "0.6.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fugue-{{ version }}.tar.gz
  sha256: c007a53e72b2d97139bbfbc21e704bdfb30a52b95f57a5a48e5c5abb7813353b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - adagio >=0.2.3
    - pandas >=1.0.2
    - pyarrow >=0.15.1
    - python >=3.7
    - qpd >=0.2.6
    - sqlalchemy
    - triad >=0.6.0

test:
  source_files:
    - tests
  imports:
    - fugue
    - fugue.collections
    - fugue.column
    - fugue.dataframe
    - fugue.execution
    - fugue.extensions
    - fugue.extensions.creator
    - fugue.extensions.outputter
    - fugue.extensions.processor
    - fugue.extensions.transformer
    - fugue.rpc
    - fugue.workflow
    - fugue_dask
    - fugue_duckdb
    - fugue_ibis
    - fugue_ibis.execution
    - fugue_notebook
    - fugue_notebook.nbextension
    - fugue_spark
    - fugue_sql
    - fugue_test
    - fugue_version
  commands:
    - pip list | grep -E '{{ name }}\s+{{ version }}'
    - SPARK_JAR=$(pip show pyspark | grep Location | cut -d' ' -f 2)
    - wget -U "Any User Agent" -O "${SPARK_JAR}/pyspark/jars/spark-avro_2.12-3.2.0.jar"  https://repo1.maven.org/maven2/org/apache/spark/spark-avro_2.12/3.2.0/spark-avro_2.12-3.2.0.jar
    - pytest -vvv --capture=tee-sys -k --ignore=fugue_spark tests
  requires:
    - antlr4-python3-runtime
    - atpublic >=2.3,<3
    - dask
    - flask
    - ibis-framework >=2
    - jinja2
    - jupyterlab
    - notebook
    - openjdk
    - pandavro
    - pip
    - pyarrow>=5.0.0
    - pyspark
    - pytest
    - python-duckdb >=0.3.1
    - qpd
    - regex >=2021.7.6,<2022.0.0
    - thrift ==0.11.0
    - wget

about:
  home: http://github.com/fugue-project/fugue
  summary: An abstraction layer for distributed computation
  license: Apache-2.0
  license_file: LICENSE  # license file manually packaged.
  description: |
    Fugue is a unified interface for distributed computing that lets
     users execute Python, pandas, and SQL code on Spark and Dask
     without rewrites. It is meant for data scientists/analysts who want
     to focus on defining logic rather than worrying about execution. It
     is also suitable for SQL users wanting to use SQL to define
     end-to-end workflows in pandas, Spark, and Dask. Data scientists
     using pandas wanting to take advantage of Spark or Dask with
     minimal effort, as well as big data practitioners finding testing
     code to be costly and slow would also find Fugue useful.


extra:
  recipe-maintainers:
    - thewchan
