{% set name = "fugue" %}
{% set version = "0.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fugue-{{ version }}.tar.gz
  sha256: d1cbe61d812378d61d65d6fbcef3a6d87ed7a5ca244504434af65245d1b08494

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - adagio >=0.2.4
    - triad >=0.9.7

test:
  imports:
    - fugue
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/fugue-project/fugue
  doc_url: https://fugue-tutorials.readthedocs.io/
  summary: An abstraction layer for distributed computation
  license: Apache-2.0
  license_file: LICENSE  # license file manually packaged.
  description: |
    Fugue is a unified interface for distributed computing that lets
     users execute Python, pandas, and SQL code on Spark and Dask
     without rewrites. It is meant for data scientists/analysts who want
     to focus on defining logic rather than worrying about execution. It
     is also suitable for SQL users wanting to use SQL to define
     end-to-end workflows in pandas, Spark, and Dask. Data scientists
     using pandas wanting to take advantage of Spark or Dask with
     minimal effort, as well as big data practitioners finding testing
     code to be costly and slow would also find Fugue useful.


extra:
  recipe-maintainers:
    - kvnkho
    - goodwanghan
    - charlesbluca
    - thewchan
