schema_version: 1

context:
  name: fugue
  version: 0.9.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fugue-${{ version }}.tar.gz
  sha256: afa99b41872fe2087cfedf8b391a60c20443360fd1ba9c87479369c0356006f9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - triad >=1.0.0
    - adagio >=0.2.6

tests:
  - python:
      imports:
        - fugue
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: An abstraction layer for distributed computation
  license: Apache-2.0
  license_file: LICENSE  # license file manually packaged.
  description: |
    Fugue is a unified interface for distributed computing that lets
    users execute Python, pandas, and SQL code on Spark and Dask
    without rewrites. It is meant for data scientists/analysts who want
    to focus on defining logic rather than worrying about execution. It
    is also suitable for SQL users wanting to use SQL to define
    end-to-end workflows in pandas, Spark, and Dask. Data scientists
    using pandas wanting to take advantage of Spark or Dask with
    minimal effort, as well as big data practitioners finding testing
    code to be costly and slow would also find Fugue useful.



  homepage: http://github.com/fugue-project/fugue
  documentation: https://fugue-tutorials.readthedocs.io/

extra:
  recipe-maintainers:
    - kvnkho
    - goodwanghan
    - charlesbluca
    - thewchan
